twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        app_name: '%env(APP_NAME)%'
        app_supported_locales: '%env(APP_SUPPORTED_LOCALES)%'
